import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { ReportViolationUseCase, ReportViolationCommand } from "@/Application/UseCases/ReportViolationUseCase";
import { PrismaViolationRepository } from "@/Infrastructure/Persistence/Repositories/PrismaViolationRepository";
import { ViolationRoutingService } from "@/Infrastructure/Services/ViolationRoutingService";
import { ConsoleAuditAdapter } from "@/Infrastructure/External/ConsoleAuditAdapter";
import { ConsoleNotificationAdapter } from "@/Infrastructure/External/ConsoleNotificationAdapter";
import { SystemClock } from "@/Infrastructure/External/SystemClock";
import { prisma } from "@/Infrastructure/Persistence/prismaClient";
import { ViolationType } from "@/Domain/ValueObjects/ViolationType";
import { ViolationSeverity } from "@/Domain/Entities/Violation";
import { buildSecurityContext } from "@/Presentation/Middleware/buildSecurityContext";

/**
 * Validation schema for report violation request
 */
const ReportViolationSchema = z.object({
  individualId: z.string().optional().nullable(),
  violationType: z.enum([
    // Temporal
    ViolationType.ETA_OVERSTAY,
    ViolationType.EXPIRED_PERMIT,
    ViolationType.BREACH_OF_CONDITIONS,
    // Integrity
    ViolationType.DOCUMENT_FORGERY,
    ViolationType.MATERIAL_MISREPRESENTATION,
    ViolationType.FAILURE_TO_NOTIFY,
    // Regulatory
    ViolationType.FAILURE_TO_REGISTER,
    ViolationType.ILLEGAL_EMPLOYMENT,
    ViolationType.ILLEGAL_HIRING,
    ViolationType.DOCUMENT_REJECTION_FOLLOWUP,
    // Security
    ViolationType.PROHIBITED_IMMIGRANT,
    ViolationType.CRIMINAL_CONVICTION,
    ViolationType.THREAT_TO_NATIONAL_SECURITY,
  ] as const),
  severity: z.enum([
    ViolationSeverity.LOW,
    ViolationSeverity.MEDIUM,
    ViolationSeverity.HIGH,
    ViolationSeverity.CRITICAL,
  ] as const),
  description: z.string().min(10).max(1000),
});

type ReportViolationRequest = z.infer<typeof ReportViolationSchema>;

/**
 * POST /api/public/report-violation
 *
 * Public endpoint for reporting immigration violations.
 * Accepts anonymous reports and authenticated officer reports.
 *
 * Categorizes violations into 4 Legal Domains:
 * 1. Temporal (Status & Duration)
 * 2. Integrity (Documentary & Identity)
 * 3. Regulatory (Compliance & Administrative)
 * 4. Security (High Priority)
 *
 * Implements intelligent auto-routing based on domain and severity.
 */
export async function POST(request: NextRequest) {
  try {
    // Parse request body
    const body = await request.json();

    // Validate input
    const validation = ReportViolationSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        {
          error: "Invalid request",
          details: validation.error.flatten(),
        },
        { status: 400 },
      );
    }

    const input: ReportViolationRequest = validation.data;

    // Extract actor context (for authenticated reports)
    const securityContext = buildSecurityContext(request.headers);

    // Build use case dependencies
    const violationRepository = new PrismaViolationRepository(prisma);
    const routingService = new ViolationRoutingService();
    const auditPort = new ConsoleAuditAdapter();
    const notificationPort = new ConsoleNotificationAdapter();
    const clockPort = new SystemClock();

    // Create use case
    const reportViolationUseCase = new ReportViolationUseCase(
      violationRepository,
      routingService,
      securityContext,
      auditPort,
      notificationPort,
      clockPort,
    );

    // Execute use case
    const result = await reportViolationUseCase.execute({
      individualId: input.individualId || null,
      violationType: input.violationType as ViolationType,
      severity: input.severity as ViolationSeverity,
      description: input.description,
      reportedByActorId: securityContext.actorId || null,
    } as ReportViolationCommand);

    // Return success response
    return NextResponse.json(
      {
        success: true,
        violationId: result.violationId,
        routing: {
          domain: result.routing.domain,
          priority: result.routing.priority,
          targetAudience: result.routing.targetAudience,
          requiresImmediateEscalation: result.routing.requiresImmediateEscalation,
          autoGeneratedAction: result.routing.autoGeneratedAction,
          notificationsSent: result.routing.notificationRecipient ? 1 : 0,
        },
        message: "Violation reported successfully and routed for processing",
      },
      { status: 201 },
    );
  } catch (error) {
    console.error("Error reporting violation:", error);

    const errorMessage = error instanceof Error ? error.message : "Unknown error";

    return NextResponse.json(
      {
        error: "Failed to report violation",
        message: errorMessage,
      },
      { status: 500 },
    );
  }
}

/**
 * GET /api/public/report-violation
 *
 * Returns documentation about violation types and domains.
 */
export async function GET() {
  return NextResponse.json({
    endpoint: "/api/public/report-violation",
    method: "POST",
    description:
      "Report an immigration law violation. Violations are automatically categorized into 4 legal domains and routed for processing.",
    domains: {
      TEMPORAL: "Status & Duration Violations (ETA overstay, expired permits, breach of conditions)",
      INTEGRITY: "Documentary & Identity Violations (forgery, misrepresentation, failure to notify)",
      REGULATORY: "Compliance & Administrative Violations (failure to register, illegal employment)",
      SECURITY: "Security & Public Interest Violations (prohibited immigrant, criminal conviction, terrorism threat)",
    },
    violationTypes: {
      // Temporal
      ETA_OVERSTAY: "Remaining in Kenya beyond authorized period",
      EXPIRED_PERMIT: "Failure to renew work, study, or residency permit",
      BREACH_OF_CONDITIONS: "Unauthorized activities under visa type",
      // Integrity
      DOCUMENT_FORGERY: "Submission of altered or fake documents",
      MATERIAL_MISREPRESENTATION: "False information in application",
      FAILURE_TO_NOTIFY: "Not notifying Immigration of address/employer/marital status changes",
      // Regulatory
      FAILURE_TO_REGISTER: "Foreign national failing to register after 90 days",
      ILLEGAL_EMPLOYMENT: "Individual working without permit",
      ILLEGAL_HIRING: "Kenyan employer hiring undocumented person",
      DOCUMENT_REJECTION_FOLLOWUP: "Failure to leave or appeal after document rejection",
      // Security
      PROHIBITED_IMMIGRANT: "Previously deported or blacklisted person attempting re-entry",
      CRIMINAL_CONVICTION: "Non-citizen convicted of offense punishable by 3+ years imprisonment",
      THREAT_TO_NATIONAL_SECURITY: "Involvement in terrorism, espionage, or organized crime",
    },
    severities: ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
    exampleRequest: {
      method: "POST",
      url: "/api/public/report-violation",
      body: {
        individualId: "john@example.com",
        violationType: "ETA_OVERSTAY",
        severity: "HIGH",
        description: "Individual has remained in Kenya 6 months beyond ETA expiration date",
      },
    },
    exampleResponse: {
      success: true,
      violationId: "550e8400-e29b-41d4-a716-446655440000",
      routing: {
        domain: "TEMPORAL",
        priority: "HIGH",
        targetAudience: "SUPERVISOR",
        requiresImmediateEscalation: true,
        autoGeneratedAction: "Notice to Regularize or Voluntary Departure Letter",
        notificationsSent: 2,
      },
      message: "Violation reported successfully and routed for processing",
    },
    autoRoutingLogic: {
      TEMPORAL_LOW_MEDIUM: "SMS notification to individual + SMS reminder",
      TEMPORAL_HIGH_CRITICAL: "SMS + escalate to supervisor + generate notice letter",
      INTEGRITY_ANY: "Officer review + document verification + possible record lock if critical",
      REGULATORY_LOW_MEDIUM: "Officer review + scheduled compliance check",
      REGULATORY_HIGH_CRITICAL: "Escalate to supervisor + compliance review + possible record lock",
      SECURITY_ANY: "IMMEDIATE DIRECTOR NOTIFICATION + lock individual record + security ops alert",
    },
  });
}
