import { Violation } from "../../Domain/Entities/Violation";
import { ViolationDomain, ViolationType } from "../../Domain/ValueObjects/ViolationType";

/**
 * Result of routing a violation through the system
 */
export interface RoutingResult {
  violationId: string;
  domain: ViolationDomain;
  requiresImmediateEscalation: boolean;
  targetAudience: "SMS" | "OFFICER" | "SUPERVISOR" | "DIRECTOR" | "NONE";
  autoGeneratedAction: string;
  lockIndividualRecord: boolean;
  priority: "CRITICAL" | "HIGH" | "NORMAL" | "LOW";
  notificationRecipient: string | null;
  notificationMessage: string;
}

/**
 * ViolationRoutingService - Infrastructure Service
 * 
 * Coordinates the routing of violations through ICMS based on:
 * - Legal domain (Temporal, Integrity, Regulatory, Security)
 * - Severity level
 * - Business rules and escalation policies
 * 
 * Generates notifications and auto-actions based on violation classification.
 */
export class ViolationRoutingService {
  /**
   * Process a violation and determine routing channels
   */
  processViolation(violation: Violation): RoutingResult {
    const routing = violation.computeRoutingDecision();

    // Build notification based on routing decision
    const { recipient, message } = this.buildNotification(violation, routing.targetAudience);

    return {
      violationId: violation.getId(),
      domain: violation.getDomain(),
      requiresImmediateEscalation: routing.requiresImmediateEscalation,
      targetAudience: routing.targetAudience,
      autoGeneratedAction: routing.autoGeneratedAction || "Case under review",
      lockIndividualRecord: routing.lockIndividualRecord || false,
      priority: routing.priority,
      notificationRecipient: recipient,
      notificationMessage: message,
    };
  }

  /**
   * Build notification for violation
   */
  private buildNotification(
    violation: Violation,
    targetAudience: string,
  ): { recipient: string | null; message: string } {
    switch (targetAudience) {
      case "SMS":
        // Temporal violations: Send SMS to notify individual
        return {
          recipient: violation.getIndividualId() || null,
          message: this.generateSMSMessage(violation),
        };

      case "OFFICER":
        // Integrity violations: Alert assigned officer
        return {
          recipient: "OFFICER_TEAM",
          message: this.generateOfficerAlertMessage(violation),
        };

      case "SUPERVISOR":
        // Regulatory violations: Escalate to supervisor
        return {
          recipient: "SUPERVISOR",
          message: this.generateSupervisorAlertMessage(violation),
        };

      case "DIRECTOR":
        // Security violations: IMMEDIATE director notification
        return {
          recipient: "DIRECTOR_IMMIGRATION_AND_BORDER_CONTROL",
          message: this.generateDirectorAlertMessage(violation),
        };

      default:
        return {
          recipient: null,
          message: "",
        };
    }
  }

  /**
   * Generate SMS message for individual (Temporal violations)
   */
  private generateSMSMessage(violation: Violation): string {
    const type = violation.getType();

    switch (type) {
      case ViolationType.ETA_OVERSTAY:
        return "GoK: Your ETA has expired. Please contact Immigration or exit Kenya immediately. Visit icms.immigration.go.ke for help.";

      case ViolationType.EXPIRED_PERMIT:
        return "GoK: Your permit has expired. Renew immediately or face legal consequences. Visit icms.immigration.go.ke";

      case ViolationType.BREACH_OF_CONDITIONS:
        return "GoK: You are in breach of your visa conditions. Contact Immigration immediately. Visit icms.immigration.go.ke";

      default:
        return "GoK: An immigration compliance issue has been flagged on your record. Contact Immigration for details.";
    }
  }

  /**
   * Generate officer alert (Integrity violations)
   */
  private generateOfficerAlertMessage(violation: Violation): string {
    const type = violation.getType();
    const id = violation.getIndividualId() || "Anonymous";

    switch (type) {
      case ViolationType.DOCUMENT_FORGERY:
        return `[INTEGRITY] Document Forgery Alert: Individual ${id} - ${violation.getDescription()}`;

      case ViolationType.MATERIAL_MISREPRESENTATION:
        return `[INTEGRITY] Misrepresentation Alert: Individual ${id} - ${violation.getDescription()}`;

      case ViolationType.FAILURE_TO_NOTIFY:
        return `[INTEGRITY] Failure to Notify Alert: Individual ${id} - ${violation.getDescription()}`;

      default:
        return `[INTEGRITY] Alert: Individual ${id} - ${violation.getDescription()}`;
    }
  }

  /**
   * Generate supervisor alert (Regulatory violations)
   */
  private generateSupervisorAlertMessage(violation: Violation): string {
    const type = violation.getType();
    const id = violation.getIndividualId() || "Anonymous";

    switch (type) {
      case ViolationType.FAILURE_TO_REGISTER:
        return `[REGULATORY] Individual ${id} failed to register within 90 days - ${violation.getDescription()}`;

      case ViolationType.ILLEGAL_EMPLOYMENT:
        return `[REGULATORY] Illegal employment case - Individual ${id} - ${violation.getDescription()}`;

      case ViolationType.ILLEGAL_HIRING:
        return `[REGULATORY] Illegal hiring case - Individual ${id} - ${violation.getDescription()}`;

      case ViolationType.DOCUMENT_REJECTION_FOLLOWUP:
        return `[REGULATORY] Document rejection follow-up required - Individual ${id} - ${violation.getDescription()}`;

      default:
        return `[REGULATORY] Alert: Individual ${id} - ${violation.getDescription()}`;
    }
  }

  /**
   * Generate director alert (Security violations)
   */
  private generateDirectorAlertMessage(violation: Violation): string {
    const type = violation.getType();
    const id = violation.getIndividualId() || "Anonymous";
    const timestamp = new Date().toISOString();

    switch (type) {
      case ViolationType.PROHIBITED_IMMIGRANT:
        return `[SECURITY CRITICAL] Prohibited Immigrant Detected - ${id} - Time: ${timestamp} - ${violation.getDescription()}`;

      case ViolationType.CRIMINAL_CONVICTION:
        return `[SECURITY CRITICAL] Criminal Conviction Alert - ${id} - Time: ${timestamp} - ${violation.getDescription()}`;

      case ViolationType.THREAT_TO_NATIONAL_SECURITY:
        return `[SECURITY CRITICAL] National Security Threat - ${id} - Time: ${timestamp} - ${violation.getDescription()}`;

      default:
        return `[SECURITY CRITICAL] Security Violation - ${id} - Time: ${timestamp} - ${violation.getDescription()}`;
    }
  }

  /**
   * Check if violation requires individual record lock
   */
  shouldLockIndividualRecord(violation: Violation): boolean {
    return violation.shouldLockIndividualRecord();
  }

  /**
   * Get human-readable routing summary
   */
  getRoutingSummary(result: RoutingResult): string {
    return `
Violation ${result.violationId}:
  Domain: ${result.domain}
  Priority: ${result.priority}
  Target: ${result.targetAudience}
  Escalation: ${result.requiresImmediateEscalation ? "YES" : "NO"}
  Lock Record: ${result.lockIndividualRecord ? "YES" : "NO"}
  Action: ${result.autoGeneratedAction}
  Notification Recipient: ${result.notificationRecipient || "NONE"}
    `;
  }
}
