import { DomainError } from "../Exceptions/DomainError";
import { ViolationType, ViolationDomain, getViolationDomain } from "../ValueObjects/ViolationType";

export enum ViolationSeverity {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum ViolationStatus {
  REPORTED = "REPORTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  ESCALATED = "ESCALATED",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED",
}

export interface ViolationRoutingDecision {
  requiresImmediateEscalation: boolean;
  targetAudience: "SMS" | "OFFICER" | "SUPERVISOR" | "DIRECTOR" | "NONE";
  autoGeneratedAction?: string;
  lockIndividualRecord?: boolean;
  priority: "CRITICAL" | "HIGH" | "NORMAL" | "LOW";
}

/**
 * Violation - Domain Entity
 * 
 * Represents a reported violation of immigration law categorized into 4 legal domains.
 * Enforces business rules for violation severity, routing, and auto-generated actions.
 */
export class Violation {
  private id: string;
  private individualId: string | null; // null for anonymous reports
  private type: ViolationType;
  private domain: ViolationDomain;
  private severity: ViolationSeverity;
  private description: string;
  private reportedByActorId: string | null; // null for anonymous/external reports
  private status: ViolationStatus;
  private createdAt: Date;
  private updatedAt: Date;
  private routingDecision: ViolationRoutingDecision | null = null;

  constructor(props: {
    id: string;
    individualId: string | null;
    type: ViolationType;
    severity: ViolationSeverity;
    description: string;
    reportedByActorId: string | null;
    status?: ViolationStatus;
    createdAt: Date;
    updatedAt: Date;
  }) {
    this.id = props.id;
    this.individualId = props.individualId;
    this.type = props.type;
    this.domain = getViolationDomain(props.type);
    this.severity = props.severity;
    this.description = props.description;
    this.reportedByActorId = props.reportedByActorId;
    this.status = props.status || ViolationStatus.REPORTED;
    this.createdAt = props.createdAt;
    this.updatedAt = props.updatedAt;

    this.validate();
  }

  private validate(): void {
    if (!this.description || this.description.trim().length === 0) {
      throw new DomainError("Violation description cannot be empty");
    }

    if (this.description.length > 1000) {
      throw new DomainError("Violation description cannot exceed 1000 characters");
    }

    // Security violations must be reported (not anonymous) or flagged for verification
    if (this.domain === ViolationDomain.SECURITY && !this.reportedByActorId) {
      // Allow anonymous security reports, but they require more scrutiny
    }
  }

  /**
   * Factory method to create a new violation
   */
  static create(props: {
    individualId: string | null;
    type: ViolationType;
    severity: ViolationSeverity;
    description: string;
    reportedByActorId: string | null;
  }): Violation {
    return new Violation({
      id: crypto.randomUUID(),
      individualId: props.individualId,
      type: props.type,
      severity: props.severity,
      description: props.description,
      reportedByActorId: props.reportedByActorId,
      status: ViolationStatus.REPORTED,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }

  /**
   * Determine routing decision based on violation domain and severity
   * Implements intelligent auto-routing logic for ICMS
   */
  computeRoutingDecision(): ViolationRoutingDecision {
    if (this.routingDecision) {
      return this.routingDecision;
    }

    // Category 1: Temporal (Status & Duration Violations)
    if (this.domain === ViolationDomain.TEMPORAL) {
      this.routingDecision = this.routeTemporalViolation();
    }
    // Category 2: Integrity (Documentary & Identity Violations)
    else if (this.domain === ViolationDomain.INTEGRITY) {
      this.routingDecision = this.routeIntegrityViolation();
    }
    // Category 3: Regulatory (Compliance & Administrative Violations)
    else if (this.domain === ViolationDomain.REGULATORY) {
      this.routingDecision = this.routeRegulatoryViolation();
    }
    // Category 4: Security (Security & Public Interest Violations)
    else if (this.domain === ViolationDomain.SECURITY) {
      this.routingDecision = this.routeSecurityViolation();
    }

    return this.routingDecision!;
  }

  /**
   * Route Temporal violations (ETA overstay, expired permits, breach of conditions)
   * Action: Auto-generate notice to regularize or voluntary departure
   */
  private routeTemporalViolation(): ViolationRoutingDecision {
    const isPriority = this.severity === ViolationSeverity.CRITICAL || this.severity === ViolationSeverity.HIGH;

    return {
      requiresImmediateEscalation: isPriority,
      targetAudience: isPriority ? "SUPERVISOR" : "SMS",
      autoGeneratedAction: "Notice to Regularize or Voluntary Departure Letter",
      lockIndividualRecord: false,
      priority: isPriority ? "HIGH" : "NORMAL",
    };
  }

  /**
   * Route Integrity violations (forgery, misrepresentation, failure to notify)
   * Action: Flag for immediate officer review and document verification
   */
  private routeIntegrityViolation(): ViolationRoutingDecision {
    return {
      requiresImmediateEscalation: this.severity === ViolationSeverity.CRITICAL,
      targetAudience: "OFFICER",
      autoGeneratedAction: "Flag for Document Verification Review",
      lockIndividualRecord: this.severity === ViolationSeverity.CRITICAL,
      priority: this.severity === ViolationSeverity.CRITICAL ? "CRITICAL" : "HIGH",
    };
  }

  /**
   * Route Regulatory violations (failure to register, illegal employment)
   * Action: Escalate to compliance officer for scheduled review
   */
  private routeRegulatoryViolation(): ViolationRoutingDecision {
    const priority = this.severity === ViolationSeverity.CRITICAL ? "CRITICAL" : "HIGH";

    return {
      requiresImmediateEscalation: this.severity === ViolationSeverity.CRITICAL,
      targetAudience: this.severity === ViolationSeverity.CRITICAL ? "SUPERVISOR" : "OFFICER",
      autoGeneratedAction: "Escalate to Compliance Officer",
      lockIndividualRecord: false,
      priority,
    };
  }

  /**
   * Route Security violations (prohibited immigrant, criminal conviction, threat to national security)
   * Action: IMMEDIATE - Lock record and notify Director of Immigration instantly
   */
  private routeSecurityViolation(): ViolationRoutingDecision {
    return {
      requiresImmediateEscalation: true,
      targetAudience: "DIRECTOR",
      autoGeneratedAction: "Lock Individual Record - Immediate Director Notification",
      lockIndividualRecord: true,
      priority: "CRITICAL",
    };
  }

  /**
   * Mark violation as under review
   */
  markAsUnderReview(): void {
    if (this.status !== ViolationStatus.REPORTED) {
      throw new DomainError(`Cannot mark violation as under review. Current status: ${this.status}`);
    }
    this.status = ViolationStatus.UNDER_REVIEW;
    this.updatedAt = new Date();
  }

  /**
   * Escalate violation (e.g., to supervisor or director)
   */
  escalate(): void {
    if (this.status === ViolationStatus.RESOLVED || this.status === ViolationStatus.DISMISSED) {
      throw new DomainError(`Cannot escalate a ${this.status.toLowerCase()} violation`);
    }
    this.status = ViolationStatus.ESCALATED;
    this.updatedAt = new Date();
  }

  /**
   * Resolve violation
   */
  resolve(): void {
    if (this.status === ViolationStatus.DISMISSED) {
      throw new DomainError("Cannot resolve a dismissed violation");
    }
    this.status = ViolationStatus.RESOLVED;
    this.updatedAt = new Date();
  }

  /**
   * Dismiss violation (e.g., false report, case closed)
   */
  dismiss(): void {
    if (this.status === ViolationStatus.RESOLVED) {
      throw new DomainError("Cannot dismiss a resolved violation");
    }
    this.status = ViolationStatus.DISMISSED;
    this.updatedAt = new Date();
  }

  // Getters
  getId(): string {
    return this.id;
  }

  getIndividualId(): string | null {
    return this.individualId;
  }

  getType(): ViolationType {
    return this.type;
  }

  getDomain(): ViolationDomain {
    return this.domain;
  }

  getSeverity(): ViolationSeverity {
    return this.severity;
  }

  getDescription(): string {
    return this.description;
  }

  getReportedByActorId(): string | null {
    return this.reportedByActorId;
  }

  getStatus(): ViolationStatus {
    return this.status;
  }

  getCreatedAt(): Date {
    return this.createdAt;
  }

  getUpdatedAt(): Date {
    return this.updatedAt;
  }

  /**
   * Check if this is a security violation requiring immediate action
   */
  isSecurityViolation(): boolean {
    return this.domain === ViolationDomain.SECURITY;
  }

  /**
   * Check if individual record should be locked due to this violation
   */
  shouldLockIndividualRecord(): boolean {
    const routing = this.computeRoutingDecision();
    return routing.lockIndividualRecord || false;
  }

  /**
   * Serialize to plain object for persistence/API responses
   */
  toPlainObject() {
    return {
      id: this.id,
      individualId: this.individualId,
      type: this.type,
      domain: this.domain,
      severity: this.severity,
      description: this.description,
      reportedByActorId: this.reportedByActorId,
      status: this.status,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
    };
  }
}
